<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * External service definitions for Edwiser Page Builder.
 *
 * @package   local_edwiserpagebuilder
 * @copyright (c) 2022 WisdmLabs (https://wisdmlabs.com/) <support@wisdmlabs.com>
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 * @author Sudam Chakor
 */

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_edwiserpagebuilder_get_media_list' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_get_media_list',
        'classpath'     => '',
        'description'   => 'List down the media files from the given context.',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_view_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_save_media_files' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_save_media_files',
        'classpath'     => '',
        'description'   => 'Saves the media files in the draft area.',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_delete_media_file' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_delete_media_file',
        'classpath'     => '',
        'description'   => 'Deletes the given media file.',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'edwiserpagebuilder_fetch_blocks_list' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_fetch_blocks_list',
        'classpath'     => '',
        'description'   => 'Fetches edwiser blocks list.',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_view_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'edwiserpagebuilder_update_block_content' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_update_block_content',
        'classpath'     => '',
        'description'   => 'Updates block content by fetching new content from json.',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_get_shortcode_parsered_html' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_get_shortcode_parsered_html',
        'classpath'     => '',
        'description'   => 'Parse shortcode and prints html output.',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_view_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_course_get_categories' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_course_get_categories',
        'classpath'     => '',
        'description'   => 'Return category details',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_view_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'edwiserpagebuilder_fetch_layout_list' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_fetch_layout_list',
        'classpath'     => '',
        'description'   => 'Fetches edwiser Layout list.',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_view_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_get_cards_list' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_get_cards_list',
        'classpath'     => '',
        'description'   => 'Return Cards Layouts List',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_view_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_delete_block' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_delete_block',
        'classpath'     => '',
        'description'   => 'Delete block',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_render_page_cards' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_render_page_cards',
        'classpath'     => '',
        'description'   => 'Render cards on modal',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_view_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_fetch_page_details' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_fetch_page_details',
        'classpath'     => '',
        'description'   => 'Read Selected card details',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_view_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_perform_page_action' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_perform_page_action',
        'classpath'     => '',
        'description'   => 'Add or Update action to be performed on pages.',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_fetch_addable_blocks' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_fetch_addable_blocks',
        'description'   => 'Returns all addable blocks in a given page.',
        'type'          => 'read',
        'capabilities'  => 'moodle/site:manageblocks, moodle/block:edit, moodle/my:manageblocks',
        'ajax'          => true,
        'loginrequired' => true,
    ],
    'local_edwiserpagebuilder_fetchblocks' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_fetchblocks',
        'description'   => 'Fetch all blocks using fetchallblocks function.',
        'type'          => 'read',
        'capabilities'  => 'moodle/site:manageblocks',
        'ajax'          => true,
        'loginrequired' => true,
    ],
    'local_edwiserpagebuilder_update_pro_blocks' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_update_pro_blocks',
        'description'   => 'Update all pro (locked) blocks content bypassing version check.',
        'type'          => 'write',
        'capabilities'  => 'moodle/site:manageblocks',
        'ajax'          => true,
        'loginrequired' => true,
    ],
    'local_edwiserpagebuilder_add_adv_block_layout' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'edwiser_add_adv_block_layout',
        'description'   => 'add block layout in a given region',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'ajax'          => true,
        'loginrequired' => true,
    ],
    'local_edwiserpagebuilder_get_frontpage_section_courses_in_category' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'get_frontpage_section_courses_in_category',
        'description'   => 'Get courses and it\'s data of category',
        'type'          => 'read',
        'loginrequired' => false,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_get_courses' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'get_courses',
        'description'   => 'Get courses based on passed arguments',
        'type'          => 'read',
        'loginrequired' => false,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_do_page_action' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'do_page_action',
        'description'   => 'All CRUD operation and other actions on pages',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_epb_fetch_layout_templates' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'epb_fetch_layout_templates',
        'description'   => 'Get courses based on passed arguments',
        'type'          => 'read',
        'loginrequired' => false,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_remuiblck_action' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'remuiblck_action',
        'description'   => 'All remui blck operation and other actions on pages',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_get_filter_plugin_status' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'filter_plugin_data',
        'description'   => 'Get filter plugin status data.',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_get_courselist' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'get_courselist',
        'description'   => 'Get courses list',
        'type'          => 'read',
        'loginrequired' => false,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_do_import_export_action' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'import_export_blocks',
        'description'   => 'import/export block content',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    // AI Block Creator services.
    'local_edwiserpagebuilder_generate_ai_block' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'generate_ai_block',
        'description'   => 'Generate block HTML/CSS/JS content from a user prompt via Moodle core AI.',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_validate_ai_prompt' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'validate_ai_prompt',
        'description'   => 'Validate a prompt for quality, security, and relevance.',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_optimize_ai_prompt' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'optimize_ai_prompt',
        'description'   => 'Optimize a user prompt using AI for better block generation.',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_update_ai_content' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'update_ai_content',
        'description'   => 'Save AI-generated HTML/CSS/JS to a block instance configdata.',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_confirm_ai_generation' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'confirm_ai_generation',
        'description'   => 'Confirm successful AI generation and increment the request count.',
        'type'          => 'write',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
    'local_edwiserpagebuilder_get_ai_requests_remaining' => [
        'classname'     => 'local_edwiserpagebuilder\external\epb_api',
        'methodname'    => 'get_ai_requests_remaining',
        'description'   => 'Get the number of AI generation requests remaining for the current user.',
        'type'          => 'read',
        'capabilities'  => 'local/edwiserpagebuilder:epb_can_manage_page',
        'loginrequired' => true,
        'ajax'          => true,
    ],
];
